train_data_path: tsp100_train_concorde.txt
val_data_path: tsp100_test_concorde.txt 
node_size: 100
train_batch_size: 1280  # [tsp50, tsp100] : 1280, [tsp500, tsp1000] : 40
val_batch_size: 1280  # [tsp50,tsp100]: 1280, [tsp500, tsp1000]: 60
test_batch_size: 1280 #128 
G: 1 # multi-start: 20 , greedy : 1 
resume_training : False
resume_checkpoint: 'tsp100_trained.ckpt' #ckpt file path
gpus: [0]  
max_epochs: 150 #tsp50 :140, tsp100 : 150, tsp500 : 500, tsp1000 : 470
enc_num_layers: 6 
dec_num_layers: 6 
d_model: 256 
d_ff: 1024 
h: 8
dropout: 0.1
smoothing: 0.1
seed: 1
lr: 0.5
betas: [0.9, 0.98]
eps: 1e-9
factor: 1.0 
warmup: 400
encoder_pe: 2D 
decoder_pe: circular 
decoder_lut: memory 
comparison_matrix: memory 
use_start_token : False
mst_loss_weight : 0.1
grad_clip : False
fuzzy_depth : 6
feat_dim : 128 # feat_dim = (fuzzy_depth*8) +80
# please modify "fuzzy_depth, feat_dim,val_data_path,G,resume_checkpoint "before run
